sudo: required
services:
  - docker

before_install:
  - docker build -t meataur/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run meataur/react-test npm test -- --coverage

after_success:
  - docker build -t meataur/multi-client  ./client
  - docker build -t meataur/multi-nginx ./nginx
  - docker build -t meataur/multi-server ./server
  - docker build -t meataur/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login --u meataur --password-stdin
  # Take those images and push them to docker hub
  - docker push meataur/multi-client
  - docker push meataur/multi-nginx
  - docker push meataur/multi-server
  - docker push meataur/multi-worker